Feature/duplicate entry
HumanSignal/label-studio pull request #3293
Opened 2022-11-23 10:51 UTC by shayantabatabaee

This pull request is related to https://github.com/heartexlabs/label-studio/issues/3292, please kindly review it.

Thanks in advance

2022-11-24 00:41 UTC, makseq requested changes
Thanks for this curious PR! 

I see at least two issues:
1. Big one: changing inner_id this way you break pipelines that already use inner_id as integer. So, it's better to rename it to unique_id
2. There should be something similar in source cloud storages:
https://github.com/heartexlabs/label-studio/pull/3293/files#diff-3829314442f71e22038252a7dd1b60e33066aa55ad7462fed59a398ad7ecb820R277

2022-11-24 00:41 UTC, makseq commented on label_studio/tasks/serializers.py
> +            all_inner_ids = [inner_id[0] for inner_id in tasks.values_list('inner_id')]
```
[inner_id[0] for inner_id in tasks.values_list('inner_id')]
```
=>
```
list(tasks.values_list('inner_id', flat=True))
```

2022-11-26 15:26 UTC, shayantabatabaee commented
Thanks for reviewing our changes, 

We reverted the commits that affected `inner_id` field, Also we added `unique_id` field for each task with same functionality. 
For the second issue, we have checked importing data through file and URL, and it seems to work fine. I would really appreciate that if you could explain more for the second issue if any further changes need to make.

2022-11-26 23:32 UTC, makseq commented
> Thanks for reviewing our changes,
> 
> We reverted the commits that affected `inner_id` field, Also we added `unique_id` field for each task with same functionality. For the second issue, we have checked importing data through file and URL, and it seems to work fine. I would really appreciate that if you could explain more for the second issue if any further changes need to make.

Thanks for updates!

https://github.com/heartexlabs/label-studio/blob/develop/label_studio/io_storages/base_models.py#L138 - check this regarding import storages. Try to add any source storage and sync tasks form there.

2022-11-27 07:26 UTC, shayantabatabaee commented
Thanks for your instruction, 

We added an ability to read `unique_id` from cloud storage source and also prevent from duplicate entry if task with same `unique_id` already exists in database.

2024-01-05 10:32 UTC, shsaronian commented
Hi, 
Adding a quick comment to prevent this pr from going stale and closing. There was no activity on our side as we are still awaiting further progress on this pr. 

Thank you

2024-06-10 15:41 UTC, farioas commented
Closed as stale

2024-06-10 15:41 UTC, closed without merging